services:
  api:
    build: .
    ports:
      - "4000:4000"
    env_file: ".env"
    volumes:
      - ./:/home/node/app
    networks:
      - foodie
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: elvis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: foodie
    networks:
      - foodie
    volumes:
      - foodie_db:/var/lib/postgresql/data
    
networks:
  foodie:
    driver: bridge

volumes:
  foodie_db:
