openapi: 3.1.0
info:
  title: Foodie API
  version: 0.0.1
  description: |-
    This is the documenation for the Foodie API.
    
    Some useful links:
    - [The Foodie repository](https://github.com/ElvisHernandez/Foodie)

servers:
  - url: http://localhost:4000/v1
tags:
  - name: Authentication
paths:
  /auth/google/signin:
    get:
      tags:
        - Authentication
      summary: Initiate Google Authorization Code Grant Flow
      description: This request will redirect to Google servers where Foodie must be authorized to retrieve google user data like email
      responses: 
        '302':
          description: Redirects to Google servers for consent
  /auth/google/callback:
    get:
      tags:
        - Authentication
      summary: Completes Google Authorization Code Grant Flow
      description: This request will exchange the auth code retrieved from the /signin route for access, refresh, and id tokens. The user is then redirected back to the client.
      responses:
        '302':
          description: Redirects back to the client that made the request.
          headers:
            Location:
              description: The URL to which the client is redirected, including the `auth_token` jwt token parameter.
              schema:
                type: string
                example: http://localhost:3000?auth_token={jwt_auth_token}
